# sudo: required
# language: node_js
# node_js:
#   - 'node'
#   - '6'

# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

# script:
#   - yarn test:travis

# addons:
#   firefox: latest
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable




#sudo: true
#dist: trusty
language: php
php:
  - 7.0

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - graphicsmagick

before_install:
- nvm install 8 # or 5, 6, or whatever
- node --version && npm --version && composer --version
#- npm update -g npm # if necessary
#- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
#- export PATH=$HOME/.yarn/bin:$PATH
- composer global require hirak/prestissimo
- if [[ -n "$GITHUB_TOKEN" ]]; then composer config -g github-oauth.github.com ${GITHUB_TOKEN};
  fi;

before_script:
- phpenv config-rm xdebug.ini

install:
- npm install && npm run setup
# - gem install --file packages/website-jekyll/Gemfile

script:
- npm run test
- travis_wait npm run build && npm run deploy # only run deploy if build is successful. Can't do `after_success` b/c if deploy fails, the build still reports success. Can't use `deploy` step b/c Travis skips that on PRs.

cache:
  apt: true
#  yarn: true
  directories:
#  - "$HOME/.cache/yarn"
#  - node_modules

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: cNto+gWAoK1JM9jBNG4i4rMSybv3twMbqlFSCohQFBDMwKFMdlyWqFDX6iYKtHxWEDzrZyRz3qiJ8/S44mgjeKJ/xHbHDtPchp/KL2P1htipvwD2EZXobcBEGl83v2rmtFO1WNJUPB3RIJE2yt1wJsX7NIXpDw82hePmaIvNJmtbLpK/J5uaFqGNHIsctmULgVmGSNSTyK4nYxxjNNLd0EvO37Y6VN8FhsKNu2NHMKeeQxinEvETDUh8XuqXZYNWE3PBvVa4OiDhgnr5K27jsnWX+wEmqg0xY+CMf7mUSTqVN61fA7LnHyM0qcGGmB6YTv4QYLMwPydp+nsjDcm3St9D+KOTsQ4ExOaEAL/6EnAEpl8GtxST+ytdqswhCC4yMCO61Hy+M5AoXgDSGrrXHgZakDMAcEVcJdH38791hRxcuM3ldVmHAlAWFdgRLG5rRMVh3qoXz7jbraoTdjyKMegQIQdKR2SX7O9Dv0EEtLz4lTFN2RENvAjLggUPPU+ESoUHmSbwmPGnt7jy3ra2AI3nnYpfn/0e6Op/A3z7HLbdm3XyuNWoTPhy1mc4Adca+HosJ37UPv7nDRIGds1sKYAeWq94+rEk+/6IQ/oRIDRhSYsQbLLWnU6DH4o7iOj7D+X/ngjqmF75nW2s5+7rtdBHFvNzOJalCKHiDTMfdlQ=
