pages:
- Home: 'index.md'
- Setup: 'setup.md'
- 'Folder Structure': 'folder-structure.md'
- Workflows:
  - 'Starting Pattern Lab': 'workflows/starting-pl.md'
  - 'Adding a new component': 'workflows/adding-a-new-component.md'
  - 'Troubleshooting': 'workflows/troubleshooting.md'