  $schema: http://json-schema.org/draft-04/schema#
  title: Bolt Button
  type: object
  required:
    - env
    - buildDir
    - components
  additionalProperties: false
  properties:
    env:
      type: string
      title: Environment Type
      description: Where is this being compiled? Pattern Lab? Drupal?
      enum:
        - pl
    plConfigFile:
      type: string
      title: Pattern Lab Config File Path
    buildDir:
      type: string
      description: Where it all builds too
    wwwDir:
      type: string
      title: Path to server root
      description: Where static files are served from.
    publicPath:
      type: string
      title: Path to publicPath directory
      description: Sets the client-side base path for all built / asynchronously loaded assets
    verbosity:
      type: integer
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
    components:
      type: object
      properties:
        global:
          type: array
          uniqueItems: true
          # array of objects
          items:
            -
              type: string
        individual:
          type: array
          uniqueItems: true
          # array of objects
          items:
            -
              type: string
    devServer:
      type: object
      properties:
        open:
          type: boolean
          description: If, after starting `npm start`, a Browser opens.
