title: Pattern Kit


namespaces:
  includes: source/_includes
  layouts: source/_layouts
  patterns: source/_patterns
  bolt: public/templates
paths:
  data:
    - ../../../bolt-website/pattern-lab/data
  schemas:
    - ../../../bolt-website/pattern-lab/schemas
  templates:
    - ../../../bolt-website/pattern-lab/templates
  docs:
    - ../../../bolt-website/pattern-lab/docs
  sg:
    - ../../../bolt-website/pattern-lab/sg

extensions:
  data: .data.json
  schemas: .schema.json
  templates: .twig
  docs: .docs.md
  sg: .sg.md

categories:
    - Pattern
    - Component
    - Layout
assets:
  css:
    - /source/styles/style.css
  js:
  footer_js:
